baseURL = 'http://godofmegane.github.io/'
languageCode = 'ja'
DefaultContentLanguage = 'ja'
title = "GODofMEGANE's Blog"
author = "GODofMEGANE"
theme = 'hugo_theme_robust'

[Params]
dateformat = 'yyyy/MM/dd'

[taxonomies]
tag = 'tags'
category = 'categories'

[markup.goldmark.renderer]