baseURL = 'http://godofmegane.github.io/'
canonifyurls = true
publishDir = "docs"
languageCode = 'ja'
DefaultContentLanguage = 'ja'
title = "GODofMEGANE's Blog"
theme = 'hugo_theme_robust'
googleAnalytics = 'UA-225430593-1'
disqusShortname = 'www-godofmegane-com'
enableGitInfo = true

[Params]
enableHighlight = false
description = "音ゲー大好きメガネの神様のブログ"
dateformat = "2006/01/02"

[params.author]
name = "GODofMEGANE"
twitter = "https://twitter.com/god_of_megane"
github = "https://github.com/GODofMEGANE"

[taxonomies]
tag = 'tags'
category = 'categories'